version: "3.8"

services:
  app:
    container_name: app
    build: ./
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    container_name: db
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
